//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Common {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Common.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ValidationException_GeoPointLatitude_Message {
            get {
                return ResourceManager.GetString("ValidationException_GeoPointLatitude_Message", resourceCulture);
            }
        }
        
        internal static string ValidationException_GeoPointLongitude_Message {
            get {
                return ResourceManager.GetString("ValidationException_GeoPointLongitude_Message", resourceCulture);
            }
        }
        
        internal static string ValidationException_Angle_Message {
            get {
                return ResourceManager.GetString("ValidationException_Angle_Message", resourceCulture);
            }
        }
        
        internal static string ValidationException_AngleMs_Message {
            get {
                return ResourceManager.GetString("ValidationException_AngleMs_Message", resourceCulture);
            }
        }
        
        internal static string ValidationException_AngleDm_Message {
            get {
                return ResourceManager.GetString("ValidationException_AngleDm_Message", resourceCulture);
            }
        }
        
        internal static string ValidationException_NaN_Message {
            get {
                return ResourceManager.GetString("ValidationException_NaN_Message", resourceCulture);
            }
        }
        
        internal static string ValidationException_IsNullOrWhiteSpace_Message {
            get {
                return ResourceManager.GetString("ValidationException_IsNullOrWhiteSpace_Message", resourceCulture);
            }
        }
        
        internal static string ValidationException_InvalidCharacters_Message {
            get {
                return ResourceManager.GetString("ValidationException_InvalidCharacters_Message", resourceCulture);
            }
        }
        
        internal static string ValidationException_FailAsOutOfRange_Message {
            get {
                return ResourceManager.GetString("ValidationException_FailAsOutOfRange_Message", resourceCulture);
            }
        }
        
        internal static string ValidationException_Unknown_Message {
            get {
                return ResourceManager.GetString("ValidationException_Unknown_Message", resourceCulture);
            }
        }
    }
}
