//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.IO.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.IO.Test.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ulog_log_small {
            get {
                object obj = ResourceManager.GetObject("ulog-log-small", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ulog_sample {
            get {
                object obj = ResourceManager.GetObject("ulog-sample", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ulog_sample_appended {
            get {
                object obj = ResourceManager.GetObject("ulog-sample-appended", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ulog_sample_appended_multiple {
            get {
                object obj = ResourceManager.GetObject("ulog-sample-appended-multiple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ulog_sample_logging_tagged_and_default_params {
            get {
                object obj = ResourceManager.GetObject("ulog-sample-logging-tagged-and-default-params", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ulog_sample_px4_events {
            get {
                object obj = ResourceManager.GetObject("ulog-sample-px4-events", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
